// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getGrid
Rcpp::NumericVector getGrid(Rcpp::IntegerVector U, Rcpp::NumericVector ftgrid);
RcppExport SEXP _peppm_getGrid(SEXP USEXP, SEXP ftgridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type U(USEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ftgrid(ftgridSEXP);
    rcpp_result_gen = Rcpp::wrap(getGrid(U, ftgrid));
    return rcpp_result_gen;
END_RCPP
}
// gibbs
Rcpp::List gibbs(Rcpp::IntegerVector U0, Rcpp::NumericVector ftgrid, Rcpp::NumericVector time, Rcpp::IntegerVector status, double a_rates, double b_rates, int cohesion, double a_beta, double b_beta, int npost, int nburnin, int nlag);
RcppExport SEXP _peppm_gibbs(SEXP U0SEXP, SEXP ftgridSEXP, SEXP timeSEXP, SEXP statusSEXP, SEXP a_ratesSEXP, SEXP b_ratesSEXP, SEXP cohesionSEXP, SEXP a_betaSEXP, SEXP b_betaSEXP, SEXP npostSEXP, SEXP nburninSEXP, SEXP nlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type U0(U0SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ftgrid(ftgridSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type status(statusSEXP);
    Rcpp::traits::input_parameter< double >::type a_rates(a_ratesSEXP);
    Rcpp::traits::input_parameter< double >::type b_rates(b_ratesSEXP);
    Rcpp::traits::input_parameter< int >::type cohesion(cohesionSEXP);
    Rcpp::traits::input_parameter< double >::type a_beta(a_betaSEXP);
    Rcpp::traits::input_parameter< double >::type b_beta(b_betaSEXP);
    Rcpp::traits::input_parameter< int >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< int >::type nburnin(nburninSEXP);
    Rcpp::traits::input_parameter< int >::type nlag(nlagSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs(U0, ftgrid, time, status, a_rates, b_rates, cohesion, a_beta, b_beta, npost, nburnin, nlag));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_peppm_getGrid", (DL_FUNC) &_peppm_getGrid, 2},
    {"_peppm_gibbs", (DL_FUNC) &_peppm_gibbs, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_peppm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
